name: matoapunch_http
description: HTTP utilities and Chopper error handling for Matoa Punch Studio packages.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  chopper: ^8.5.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^1.6.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0
